### ISSUE TITLE
Milestone 1 Feedback

### ISSUE THREAD

**Issue by andytai7** [UBC-MDS/fxtracker#22]
Group 18 

Congrats on finishing Milestone 1! We can see that you put some thought into this project. Below we list some specific feedback you can use to improve your project.
We provide tick boxes for you to use in the future as you address these concerns to improve the final grade of your project.
If anything is unclear, please feel free to ask questions in this issue thread.

- [x] There isn't an issue by function in the package - mechanics -2

- [x] Not all the team members have been assigned to an issue (this should be function specific and also each individual should have a unique issue) - mechanics -2

- [x] There are no branches created or the branches have names that are not meaningful/descriptive of the work being done on that branch (For example toml, contributing branches should be merged and deleted after using them. The only branches really necessary are the functions branches) - mechanics -2

Remember to create issues based on functions, and assign them to team members! As a side note remember to have every member commit in the GitHub repo equally. Great job on spreading out the commits for each person. Great job on finishing the project structure. Well done, and I look forward to seeing this project progress.

**Comment by markusnam** [comment]
Fixed the 3 issues raised.
